config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:sessions], controllers: { registrations: 'registrations' }
  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  root 'projects#index'
  resources :projects, shallow: true do
    resources :chapters
  end
  get '/translations/:id', to: 'translations#create', as: :generate
  put '/phrases/:id', to: 'phrases#update'

  resources :options
  resources :users, only: [:index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :chapters, dependent: :destroy
  belongs_to :user
  validates :name, presence: true

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  def index
    @pagy, @projects = pagy(Project.includes(:user).order(:created_at))
  end

  def show
    @pagy, @chapters = pagy(@project.chapters.with_attached_chapter_file)
  end

  def new
    @project = current_user.projects.new
  end

  def create
    @project = current_user.projects.new(project_params)
    if @project.save
      flash[:success] = "Project was succesfully created!"
      redirect_to @project
    else
      flash[:error] = "Something went wrong!"
      render 'new'
    end
  end

  def edit
    authorize @project
  end

  def update
    authorize @project
    if @project.update(project_params)
      flash[:success] = "Project was successfully updated!"
      redirect_to @project
    else
      redirect_to @project
    end
  end

  def destroy
    authorize @project
    @project.destroy
    flash[:success] = "Project was successfully destroyed."
    redirect_to projects_url
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description, :author)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
    <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
            <% @project.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :author %><br>
      <%= f.text_field :author %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %>
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p class="subheader">
  Projects
</p>

<div class="row">
  <ul class="project-list">
    <% @projects.each do |project| %>
          <li class="project-item">
            <div class="info">
                <h4 class="text-center"><%= project.name %></h4>
                <h6 class="text-center"><%= project.author %></h6>
                <p><%= project.description.truncate 40 %></p>
                <div class="username">
                  <p><%= link_to project.user.username, project.user %></p>
                </div>
                <div class="actions">
                  <%= link_to 'Show', project, class: 'link' %>
                  <%= link_to 'Edit', edit_project_path(project), class: 'link' %>
                  <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'link'  %>
                </div>
            </div>
          </li>
    <% end %>
  </ul>
</div>
<%== pagy_nav(@pagy) if @pagy.pages > 1 %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div>
  <h3><%= @project.author %> : <%= @project.name %></h3>
  <p><%= @project.description %></p>
  <%= link_to 'Edit', edit_project_path(@project) %>
</div>

<%== pagy_nav(@pagy) if @pagy.pages > 1 %>
<div class="row">
  <h1>Chapters</h1>
  <table class="hover">
    <% @chapters.each do |chapter| %>
      <tr>
        <td><h3><%= link_to chapter.name, chapter, class: 'link' %></h3></td>
        <td>
          <%= chapter.filename %>
          <br>Status: <%= chapter.status.capitalize %>
        </td>
        <td><%= link_to("Generate", generate_path(chapter)) %></td>
        <td><%= chapter.completed_phrases_count %>/<%= chapter.phrases_count %></td>
        <% if chapter.chapter_file.attached? %>
          <td><%= link_to("Download #{chapter.filename}", rails_blob_path(chapter.chapter_file, disposition: "attachment")) %></td>
        <% end %>
        <td><%= link_to 'Delete', chapter, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
  </table>
</div>
<%= form_for([@project, @project.chapters.build]) do |f| %>
<!--
<div class="field">
    <%# f.label :name, "Создать новую часть " %><br>
    <%# f.text_field :name, placeholder: 'Введите название части' %>
</div>
-->
  <div class="field">
    <%= f.label :chapter_file, "Загрузить часть" %><br>
    <%= f.file_field :chapter_file, multiple: true, required: true, accept: ".json" %>
  </div>
  <div class="actions">
    <%= f.submit 'Загрузить', class: "button" %>
  </div>
<% end %>